### ISSUE TITLE
?mozlz4-win86.exe

### ISSUE THREAD

**Issue by a013** [jusw85/mozlz4#1]
您好 : )
請問 mozlz4.exe (mozlz4-win64.exe) 能有32位元版的嗎 (mozlz4-win32.exe/mozlz4-win86.exe)
感謝

**Comment by jusw85** [comment]
I've built a 32bit version, but it's not tested on a 32 bit machine.

https://github.com/jusw85/mozlz4/releases/download/v0.1.0/mozlz4-win32.exe

Please open a new ticket if there are any issues. Thanks!

**Comment by a013** [comment]
感謝您
可以用了: )
中秋節快樂: )
